remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme

title: "Robotic Eye Brooch"
subtitle: "User & Repair Manual"
name: "Maia Hirsch"

description: >
  User, maintenance, troubleshooting, and repair documentation
  for the Robotic Eye Brooch.

minimal_mistakes_skin: "default"

markdown: kramdown
